# Generated by Django 4.0.4 on 2022-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_salle_support_alter_user_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('SALE', 'Sale'), ('SUPPORT', 'Support')], max_length=100),
        ),
    ]
